title: ẍ xdoubledot
description: AI-powered Hall Effect Thrusters for VLEO
baseurl: ""
url: "https://xdoubledot.space"

theme: minima

minima:
  skin: dark

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

exclude:
  - README.md
  - "*.sh"
